### ISSUE TITLE
Best practice for using this on Heroku?

### ISSUE THREAD

**Issue by adamrubin** [reflection/designmodo-flatuipro-rails#10]
I'm a little confused, and hope you can help. The generator installs all of the asset files in the gem directory, instead of the application. This is fine for development mode, but if I were to push to Heroku, those assets wouldn't exist on the production server.

Am I missing something? If not, what's the recommend course of action to solve that problem?

**Comment by Theminijohn** [comment]
I'm having this Problem 2 weeks now, I send also an inquiry to Designmodo. But Nothing.. No one seems to know or want to dig deeper. Always some styles and assets are getting messed up on heroku

**Comment by jehughes** [comment]
I on Webfaction rather than Heroku but my solution was to add the command `rails generate flatuipro:install ~/dir` to my Capistrano deployment script.

For me personally, I like that the assets are kept in the gem rather than being mixed in with the app's asset dir. Makes them easier to identify (to remove when the time comes), I don't have to deal with them in the `.gitignore`, and I get a sort of version control with each gem update.

**Comment by reflection** [comment]
I'm hoping that if I resolve #8 Heroku issues will also be resolved.

As you all surmised, this issue pops up because I don't package the Flat UI Pro assets in the gem.  I can't because it's against the license (that's why the assets have to be copied over).

Assuming I could get the assets installed correctly in the rails app, you would then no longer need to include the gem itself.

I'll keep this issue open.  After #8 is resolved, people using Heroku could let me know if this is fixed as well.

Of course, if you want this fixed quicker, please send me a pull request.  Still crunched at both my jobs (9-5 and startup).

**Comment by patrickespake** [comment]
+1

**Comment by akshatpradhan** [comment]
:+1:

**Comment by reflection** [comment]
With v1.1.3.1, when I precompile assets, add the public/assets dir to git and push to heroku, everything works.

``` bash
RAILS_ENV=production rake assets:precompile
```
